#!/bin/bash

rm bin/hooker.so 2>/dev/null

echo "[+] Building hooker.so"
$CXX                                            \
    src/sly_cooper.cc                           \
    src/read_hooks.cc                           \
    bin/libimgui.a                              \
       											\
    -g											\
    -shared                                     \
    -o bin/hooker.so 		                    \
    -fPIC                                       \
    -std=c++20                                  \
                                                \
    -Isrc                                       \
    -Ilib/imgui                                 \
                                                \
    -lGLEW                                      \
    -ldl                                        \

echo "[+] Done building."
