#!/bin/bash

mkdir bin/obj 2>/dev/null

rm bin/hook_generator 2>/dev/null

CXX=g++

echo "[+] Building hook headers..."
$CXX src/hook_generator.cc -o bin/hook_generator -std=c++20 -ldl -Isrc && bin/hook_generator /usr/include/GL/glew.h > src/hooks.h

echo "[+] Done."
